### ISSUE TITLE
Crashes with Homey v2

### ISSUE THREAD

**Issue by KRiZ-R** [kerkenit/nl.marcovantklooster.sshclient#4]
Hi, I can not connect to my Synology NAS, the app crashes instantly when trying to connect.
6109A5E2FF

**Comment by jorgelr** [comment]
@kerkenit would you be willing to accept donations to get this working on firmware v2?

**Comment by kerkenit** [comment]
@jorgelr I've a own company and can manage my own time, so yes when you support me I would like to develop for V2. 
On the other hand, my Homey isn't updated so it's difficult to test. 
I'm not a early adopter on updates so it have to wait until there is a stable-stable version

**Comment by jorgelr** [comment]
@kerkenit I understand. Yell if you start looking at the v2, and at least I'll contribute with some money. I would love this plugin to work there:)

**Comment by MenneBos** [comment]
Tx @Kerkenit for you willingness to update the SSH client. I use it to automate the start of my favorite music (Spotify and Internet Radio).

**Comment by poblom** [comment]
@kerkenit Also willing to donate to have a working version of the ssh client!!

**Comment by MenneBos** [comment]
Check out the Pull Request from bvdbos to install the app successfully on the homey 2.0.

**Comment by MenneBos** [comment]
This is only via the CLI method

**Comment by jimvlambe** [comment]
After installing bvdbos' version I was able to create the SSH device for my server but when I tried to use it in a flow on "Search for a device" it simply shows a white screen and sits there doing nothing.

**Comment by xxxPizzakingxxx** [comment]
> 
> 
> After installing bvdbos' version I was able to create the SSH device for my server but when I tried to use it in a flow on "Search for a device" it simply shows a white screen and sits there doing nothing.

The app is not yet made ready for homey V2.0 Jim.
She post above from kerkenit.

**Comment by bochove** [comment]
all of  a sudden this app started working again! Just not when it's the only card in the then section.

When it is the only  app in that section I get the following error:
`SSH Client - init start
/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v1/manager/flow.js:1
(function (exports, require, module, __filename, __dirname) { var self={private:{init(){function e(e){for(const t in e){const n=e[t];"object"==typeof n&&"device"===n.__type&&(e[t]=n.data)}return e}Home
y.ready(()=>{Homey.client.on("homey:manager:flow","onRun",(t,n)=>{!1===self.public.emit(`${t.type}.${t.id}`,n,e(t.args),t.state)&&n(new Error("missing_listener"))}),Homey.client.on("homey:manager:flow"
,"onAutocomplete",(t,n)=>{t.name=t.args.name,delete t.args.name,!1===self.public.emit(`${t.type}.${t.id}.${t.name}.autocomplete`,n,e(t.args))&&n(new Error("missing_listener"))}),Homey.client.on("homey:
manager:flow","onUpdate",(t,n)=>{self.public.emit(`${t.type}.${t.id}.update`,()=>{},e(t.args));n(null,!0)})}),self.emit("ready")}},public:{trigger(e,t,n,i){if("undefinded"==typeof e)return i(new Error(
"missing id"));Homey.client.emit("homey:manager:flow","trigger",{id:e,tokens:t,state:n},i)},triggerDevice(e,t,n,i,r){if("undefinded"==type

TypeError: Cannot read property '__type' of null
    at e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v1/manager/flow.js:1:167)
    at Homey.client.on (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v1/manager/flow.js:1:312)
    at eventListeners.filter.forEach.t (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v1/helpers/client.js:1:1008)
    at Array.forEach (<anonymous>)
    at process.on.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v1/helpers/client.js:1:985)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)`

The strange thing is that when I add another version of the same app then one of the two functions while the other gives this error, that is how I figured out what this error is and that when there are two cards on the flow that this app works. As a workaround I have added a notification to the when tab, that I never receive but the ssh command is now send. Quite strange, but since I got a working ssh client now I've stopped bothering, when it starts erroring out I might just look into what causes the above error to occur.

**Comment by jimvlambe** [comment]
Following the Homey v2.2.1 update I re-installed bvdbos' version version again and it it now working for me. Yay!

**Comment by xxxPizzakingxxx** [comment]
i tried it again also with V2.2.1 not working getting ECONNRESET

**Comment by xxxPizzakingxxx** [comment]
Mmmmm after making a second ssh server with the same ip and username and password it is working.

**Comment by bochove** [comment]
You can now also test from:
https://homey.app/en-us/app/nl.marcovantklooster.sshclient/SSH-Client/test/
