### ISSUE TITLE
Homey V5

### ISSUE THREAD

**Issue by JeroenKokhuis** [kerkenit/nl.marcovantklooster.sshclient#8]
The app is not working on version 5 of Homey.

**Comment by bochove** [comment]
@JeroenKokhuis I am not sure why that is the case, but Athom states that the node_modules directory is no longer needed in the repository. The error you get is because it's not there. So perhaps there is a difference between the store and local deployments, I don't know.
https://homey.app/en-gb/blog/developers-update-homey-sdk-tools/ 

Anyways, you can 'fix' this by running 'npm i ' prior to running 'homey app install'.
This of course does require nodejs to be installed.

I guess I can understand that 'homey app install' does not do this automatically to make installing faster as any developer would have run that command manually himself anyways. Good luck testing.

**Comment by bochove** [comment]
You can now also test from:
https://homey.app/en-us/app/nl.marcovantklooster.sshclient/SSH-Client/test/
If there is something wrong with this test version, please create a new issue.
